### ISSUE TITLE
(Epic) Timeline docs microsite - De-risk headless CMS

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/docs.royalnavy.io#25]
**Acceptance Criteria:**

- [x] https://github.com/Royal-Navy/design-system/issues/1624 (Spike) Gatsby vs Next.js Bakeoff
- [x] Create boilerplate Next.js app and fetch and render Hello, World from Contentful Royal-Navy/docs.royalnavy.io#7
- [x] Model Timeline Framework documentation within Contentful Royal-Navy/docs.royalnavy.io#13
- [x] Create tickets for discrete presentational UI components to be created in Next.js codebase Royal-Navy/docs.royalnavy.io#14 
- [ ] Populate Contentful with Timeline Framework content Royal-Navy/docs.royalnavy.io#15
- [ ] Spike: Investigate solution for embedding components in docs site #16
- [x] Layout (Presentational) #51
- [x] Sidebar (Presentational) #50
- [x] Hero (Presentational) #49
- [x] Masthead (Presentational) #48
- [x] Live Example (Presentational) #47
- [x] Code Block (Presentational) #46
- [x] API Table (Presentational) #45
- [x] Content Panel (Presentational) #44
