### ISSUE TITLE
(Epic) Docs site content (information architecture)

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/docs.royalnavy.io#26]
## Work Items
**Documentation:**
- [x] (IA) Review other design systems content IA Royal-Navy/docs.royalnavy.io#3
- [x] (IA) User research (customers) - Docs site "what's missing?" Royal-Navy/docs.royalnavy.io#5
- [x] (IA) User research (DS team) - Docs site "what's missing?" Royal-Navy/docs.royalnavy.io#6
- [x] (IA) Prototype IA structure Royal-Navy/docs.royalnavy.io#4
- [x] (IA) Research report of findings Royal-Navy/docs.royalnavy.io#2
- [x] (IA) Alpha prototype backlog Royal-Navy/docs.royalnavy.io#1
- [x] (IA) Audit exiting content #28
